spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:}
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sundaeswap_scooper}
    user: ${DB_USERNAME:sundaeswap}
    password: ${DB_PASSWORD:password}
    schemas: ${DB_SCHEMA:}
    locations:
      - classpath:db/store/{vendor}
      - classpath:db/store/sundaeswap
    out-of-order: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sundaeswap_scooper}
    username: ${DB_USERNAME:sundaeswap}
    password: ${DB_PASSWORD:password}


store:
  cardano:
    host: relays-new.cardano-mainnet.iohk.io
    port: 3001
    protocol-magic: 764824073
    # Start from the block that minted the ref input for the contract
    sync-start-slot: 123706722
    sync-start-blockhash: 09fde708bac045ac54d1f9e2f215e6c235518d1c43b39b645d9fc46d51c76321
  utxo:
    pruning-enabled: true
    pruning:
      interval: 600
  blocks:
    epoch-calculation-interval=14400:  # 14400 = 4 hours

apiPrefix: /api/v1

blockfrost:
  # Can put anything here as it's not used
  url: https://cardano-mainnet.blockfrost.io/api/v0/
  key: projectId

---
spring:
  config:
    activate:
      on-profile: test
  flyway:
    url: ${DB_URL:jdbc:h2:./data/db}
    user: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  datasource:
    url: ${DB_URL:jdbc:h2:./data/db}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
---
spring:
  config:
    activate:
      on-profile: local-db
  flyway:
    url: ${DB_URL:jdbc:h2:./data/db}
    user: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  datasource:
    url: ${DB_URL:jdbc:h2:./data/db}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  h2:
    console:
      enabled: true